In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('leetcode_3400_problems_dataset.csv')

In [10]:
df['Topic_Tags'].head()

0                           Array, Hash Table
1                Linked List, Math, Recursion
2          Hash Table, String, Sliding Window
3    Array, Binary Search, Divide and Conquer
4                 String, Dynamic Programming
Name: Topic_Tags, dtype: object

In [11]:
tags_series = df['Topic_Tags'].fillna('').apply(
    lambda x: [t.strip() for t in x.split(',') if t.strip()]
)
dummies = pd.get_dummies(tags_series.explode()).groupby(level=0).sum()
dummies = (dummies > 0).astype(int)  # Ensure strict binary formatting

df_topic = pd.concat([df, dummies], axis=1)

In [12]:
df_topic

,Problem_ID,Problem_Name,Topic_Tags,Difficulty,Time_Beginner_Mins,Time_Average_Mins,Time_Expert_Mins,Array,Backtracking,Binary Search,...,Sliding Window,Sorting,Stack,String,String Matching,Topological Sort,Tree,Trie,Two Pointers,Union Find
0,1,Two Sum,"Array, Hash Table",Easy,25,12,5,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Add Two Numbers,"Linked List, Math, Recursion",Medium,55,28,12,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,Longest Substring Without Repeating Characters,"Hash Table, String, Sliding Window",Medium,55,28,12,0,0,0,...,1,0,0,1,0,0,0,0,0,0
3,4,Median of Two Sorted Arrays,"Array, Binary Search, Divide and Conquer",Hard,110,55,22,1,0,1,...,0,0,0,0,0,0,0,0,0,0
4,5,Longest Palindromic Substring,"String, Dynamic Programming",Medium,55,28,12,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3395,3396,LeetCode Problem 3396,"Recursion, Topological Sort",Easy,25,16,5,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3396,3397,LeetCode Problem 3397,"Tree, Binary Search, Recursion",Hard,134,76,34,0,0,1,...,0,0,0,0,0,0,1,0,0,0
3397,3398,LeetCode Problem 3398,"Prefix Sum, Sorting",Medium,52,30,16,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3398,3399,LeetCode Problem 3399,"Stack, Sorting",Medium,60,31,16,0,0,0,...,0,1,1,0,0,0,0,0,0,0
3399,3400,LeetCode Problem 3400,"Breadth-First Search, Tree",Easy,24,12,4,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [16]:
df_topic_diff=pd.get_dummies(df_topic,columns=['Difficulty'],dtype=int)

In [17]:
df_topic_diff

,Problem_ID,Problem_Name,Topic_Tags,Time_Beginner_Mins,Time_Average_Mins,Time_Expert_Mins,Array,Backtracking,Binary Search,Binary Search Tree,...,String,String Matching,Topological Sort,Tree,Trie,Two Pointers,Union Find,Difficulty_Easy,Difficulty_Hard,Difficulty_Medium
0,1,Two Sum,"Array, Hash Table",25,12,5,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,2,Add Two Numbers,"Linked List, Math, Recursion",55,28,12,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,3,Longest Substring Without Repeating Characters,"Hash Table, String, Sliding Window",55,28,12,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
3,4,Median of Two Sorted Arrays,"Array, Binary Search, Divide and Conquer",110,55,22,1,0,1,0,...,0,0,0,0,0,0,0,0,1,0
4,5,Longest Palindromic Substring,"String, Dynamic Programming",55,28,12,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3395,3396,LeetCode Problem 3396,"Recursion, Topological Sort",25,16,5,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
3396,3397,LeetCode Problem 3397,"Tree, Binary Search, Recursion",134,76,34,0,0,1,0,...,0,0,0,1,0,0,0,0,1,0
3397,3398,LeetCode Problem 3398,"Prefix Sum, Sorting",52,30,16,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3398,3399,LeetCode Problem 3399,"Stack, Sorting",60,31,16,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3399,3400,LeetCode Problem 3400,"Breadth-First Search, Tree",24,12,4,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0

In [ ]:
df_topic_diff