In [136]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import pickle

In [3]:
df=pd.read_csv('leetcode_3400_problems_dataset.csv')

In [5]:
tags_series = df['Topic_Tags'].fillna('').apply(
    lambda x: [t.strip() for t in x.split(',') if t.strip()]
)
dummies = pd.get_dummies(tags_series.explode()).groupby(level=0).sum()
dummies = (dummies > 0).astype(int)  

df_topic = pd.concat([df, dummies], axis=1)

In [7]:
df_topic_diff=pd.get_dummies(df_topic,columns=['Difficulty'],dtype=int)

In [9]:
df_topic_diff_filtercol=df_topic_diff.drop(columns=['Topic_Tags','Problem_Name','Problem_ID'])

In [10]:
df_topic_diff_filtercol_beg=df_topic_diff_filtercol.drop(columns=['Time_Average_Mins','Time_Expert_Mins'])
df_topic_diff_filtercol_med=df_topic_diff_filtercol.drop(columns=['Time_Expert_Mins','Time_Beginner_Mins'])
df_topic_diff_filtercol_exp=df_topic_diff_filtercol.drop(columns=['Time_Beginner_Mins','Time_Average_Mins'])

In [11]:
Y=df_topic_diff_filtercol_beg['Time_Beginner_Mins']

In [12]:
X=df_topic_diff_filtercol_beg.drop(columns=['Time_Beginner_Mins'])

In [13]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42,shuffle=True)

In [14]:
model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)

In [15]:
model.fit(X_train,Y_train)

RandomForestRegressor(n_jobs=-1, random_state=42)

In [137]:
model_filename = "beginner_model.pkl"
with open(model_filename, "wb") as file:
    pickle.dump(model, file)

In [16]:
Y_pred=model.predict(X_test)

In [17]:
mae = mean_absolute_error(Y_test, Y_pred)
mse = mean_squared_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

In [18]:
mae

9.589918933991246

In [19]:
mse

169.7205018024446

In [41]:
r2

0.8643286279169834

In [77]:
df_data=pd.read_csv("striver_a2z_beginner_formatted.csv")

In [88]:
df_data.rename(columns={'Leetcode(more priority)/geeks for geeks link of corresponding problem':'Link'},inplace=True)

In [90]:
df_data['Difficulty'].unique()

array(['Easy', 'Medium'], dtype=object)

In [89]:
df_data

,Problem name,Multi topic tags,Difficulty,Link
0,User Input / Output,"Basics, Input-Output",Easy,https://www.geeksforgeeks.org/problems/input-o...
1,Data Types,"Basics, Data Types",Easy,https://www.geeksforgeeks.org/problems/data-ty...
2,If Else statements,"Basics, Conditionals",Easy,https://www.geeksforgeeks.org/problems/java-if...
3,Switch Statement,"Basics, Conditionals",Easy,https://www.geeksforgeeks.org/problems/java-sw...
4,Find Pattern 1 to 22,"Basics, Patterns, Loops",Easy,https://takeuforward.org/strivers-a2z-dsa-cour...
...,...,...,...,...
138,Longest Common Subsequence,"Dynamic Programming, Strings",Medium,https://leetcode.com/problems/longest-common-s...
139,Longest Increasing Subsequence,"Dynamic Programming, Binary Search",Medium,https://leetcode.com/problems/longest-increasi...
140,Partition Array for Maximum Sum,"Dynamic Programming, Arrays",Medium,https://leetcode.com/problems/partition-array-...
141,Longest String with All Prefixes,"Trie, Strings",Medium,https://www.geeksforgeeks.org/problems/longest...
142,Number of Distinct Substrings in a String,"Trie, Strings",Medium,https://www.geeksforgeeks.org/problems/count-o...

In [86]:
df_data_problem=df_data['Problem name']
df_data_link=df_data['Difficulty']

In [84]:
df_data_problem

0                            User Input / Output
1                                     Data Types
2                             If Else statements
3                               Switch Statement
4                           Find Pattern 1 to 22
                         ...
138                   Longest Common Subsequence
139               Longest Increasing Subsequence
140              Partition Array for Maximum Sum
141             Longest String with All Prefixes
142    Number of Distinct Substrings in a String
Name: Problem name, Length: 143, dtype: object

In [71]:
random_row=df_data_filter.sample(n=1)

In [72]:
random_row

,Step,Category,Problem Name,Problem Link,Primary Topic,LeetCode Topics,Difficulty,Acceptance Rate (%),Time (Beginner) [min],Time (Medium) [min],Time (Expert) [min]
79,Step 4,Binary Search,Count Occurrences in Sorted Array,https://leetcode.com/problems/count-occurrence...,BS 1D,"Array, Binary Search",Medium,58,25,10,4

In [73]:
tags_series = random_row['LeetCode Topics'].fillna('').apply(
    lambda x: [t.strip() for t in x.split(',') if t.strip()]
)
dummies = pd.get_dummies(tags_series.explode()).groupby(level=0).sum()
dummies = (dummies > 0).astype(int)  

random_row = pd.concat([random_row, dummies], axis=1)

In [74]:
random_row

,Step,Category,Problem Name,Problem Link,Primary Topic,LeetCode Topics,Difficulty,Acceptance Rate (%),Time (Beginner) [min],Time (Medium) [min],Time (Expert) [min],Array,Binary Search
79,Step 4,Binary Search,Count Occurrences in Sorted Array,https://leetcode.com/problems/count-occurrence...,BS 1D,"Array, Binary Search",Medium,58,25,10,4,1,1

In [103]:
df_beg=pd.read_csv('striver_a2z_beginner_formatted.csv')

In [104]:
df_beg

,Problem name,Multi topic tags,Difficulty,Leetcode(more priority)/geeks for geeks link of corresponding problem
0,User Input / Output,NaN,Easy,https://www.geeksforgeeks.org/problems/input-o...
1,Data Types,NaN,Easy,https://www.geeksforgeeks.org/problems/data-ty...
2,If Else statements,NaN,Easy,https://www.geeksforgeeks.org/problems/java-if...
3,Switch Statement,NaN,Easy,https://www.geeksforgeeks.org/problems/java-sw...
4,Find Pattern 1 to 22,NaN,Easy,https://takeuforward.org/strivers-a2z-dsa-cour...
...,...,...,...,...
138,Longest Common Subsequence,"Dynamic Programming, String",Medium,https://leetcode.com/problems/longest-common-s...
139,Longest Increasing Subsequence,"Binary Search, Dynamic Programming",Medium,https://leetcode.com/problems/longest-increasi...
140,Partition Array for Maximum Sum,"Array, Dynamic Programming",Medium,https://leetcode.com/problems/partition-array-...
141,Longest String with All Prefixes,"String, Trie",Medium,https://www.geeksforgeeks.org/problems/longest...
142,Number of Distinct Substrings in a String,"String, Trie",Medium,https://www.geeksforgeeks.org/problems/count-o...

In [105]:
tags_series = df_beg['Multi topic tags'].fillna('').apply(
    lambda x: [t.strip() for t in x.split(',') if t.strip()]
)
dummies = pd.get_dummies(tags_series.explode()).groupby(level=0).sum()
dummies = (dummies > 0).astype(int)  

df_beg_multi = pd.concat([df_beg, dummies], axis=1)

In [107]:
df_beg_multi_diff=pd.get_dummies(df_beg_multi,columns=['Difficulty'],dtype=int)

In [109]:
df_beg_multi_diff['Difficulty_Hard']=0

In [112]:
df_beg_multi_diff.rename(columns={'Leetcode(more priority)/geeks for geeks link of corresponding problem':'Link'},inplace=True)

In [114]:
df_beg_multi_diff.columns

Index(['Problem name', 'Multi topic tags', 'Link', 'Array', 'Binary Search',
       'Binary Search Tree', 'Binary Tree', 'Bit Manipulation',
       'Breadth-First Search', 'Depth-First Search', 'Divide and Conquer',
       'Dynamic Programming', 'Graph', 'Greedy', 'Hash Table',
       'Heap (Priority Queue)', 'Linked List', 'Math', 'Matrix', 'Memoization',
       'Monotonic Stack', 'Prefix Sum', 'Recursion', 'Simulation',
       'Sliding Window', 'Sorting', 'Stack', 'String', 'String Matching',
       'Tree', 'Trie', 'Two Pointers', 'Union Find', 'Difficulty_Easy',
       'Difficulty_Medium', 'Difficulty_Hard'],
      dtype='object')

In [115]:
X.columns

Index(['Array', 'Backtracking', 'Binary Search', 'Binary Search Tree',
       'Binary Tree', 'Bit Manipulation', 'Breadth-First Search',
       'Combinatorics', 'Database', 'Depth-First Search', 'Divide and Conquer',
       'Dynamic Programming', 'Graph', 'Greedy', 'Hash Table',
       'Heap (Priority Queue)', 'Linked List', 'Math', 'Matrix', 'Memoization',
       'Monotonic Stack', 'Prefix Sum', 'Recursion', 'Segment Tree',
       'Simulation', 'Sliding Window', 'Sorting', 'Stack', 'String',
       'String Matching', 'Topological Sort', 'Tree', 'Trie', 'Two Pointers',
       'Union Find', 'Difficulty_Easy', 'Difficulty_Hard',
       'Difficulty_Medium'],
      dtype='object')

In [117]:
df_beg_multi_diff_filter=df_beg_multi_diff.drop(columns=['Problem name', 'Multi topic tags'])

In [152]:
df_beg_multi_diff_filter.columns

Index(['Array', 'Backtracking', 'Binary Search', 'Binary Search Tree',
       'Binary Tree', 'Bit Manipulation', 'Breadth-First Search',
       'Combinatorics', 'Database', 'Depth-First Search', 'Divide and Conquer',
       'Dynamic Programming', 'Graph', 'Greedy', 'Hash Table',
       'Heap (Priority Queue)', 'Linked List', 'Math', 'Matrix', 'Memoization',
       'Monotonic Stack', 'Prefix Sum', 'Recursion', 'Segment Tree',
       'Simulation', 'Sliding Window', 'Sorting', 'Stack', 'String',
       'String Matching', 'Topological Sort', 'Tree', 'Trie', 'Two Pointers',
       'Union Find', 'Difficulty_Easy', 'Difficulty_Hard',
       'Difficulty_Medium'],
      dtype='object')

In [119]:
df_beg_multi_diff_filter_link=df_beg_multi_diff_filter['Link']

In [120]:
df_beg_multi_diff_filter.drop(columns=['Link'],inplace=True)

In [121]:
df_beg_multi_diff_filter.columns

Index(['Array', 'Binary Search', 'Binary Search Tree', 'Binary Tree',
       'Bit Manipulation', 'Breadth-First Search', 'Depth-First Search',
       'Divide and Conquer', 'Dynamic Programming', 'Graph', 'Greedy',
       'Hash Table', 'Heap (Priority Queue)', 'Linked List', 'Math', 'Matrix',
       'Memoization', 'Monotonic Stack', 'Prefix Sum', 'Recursion',
       'Simulation', 'Sliding Window', 'Sorting', 'Stack', 'String',
       'String Matching', 'Tree', 'Trie', 'Two Pointers', 'Union Find',
       'Difficulty_Easy', 'Difficulty_Medium', 'Difficulty_Hard'],
      dtype='object')

In [122]:
df_beg_multi_diff_filter_temp=df_beg_multi_diff_filter[df_beg_multi_diff_filter['Array']==1]

In [132]:
temp_row=df_beg_multi_diff_filter_temp.sample(n=1)

In [133]:
temp_row

,Array,Binary Search,Binary Search Tree,Binary Tree,Bit Manipulation,Breadth-First Search,Depth-First Search,Divide and Conquer,Dynamic Programming,Graph,...,Stack,String,String Matching,Tree,Trie,Two Pointers,Union Find,Difficulty_Easy,Difficulty_Medium,Difficulty_Hard
15,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0

In [155]:
v=temp_row.index[0]

In [156]:
v

np.int64(15)

In [138]:

training_columns = ['Array', 'Backtracking', 'Binary Search', 'Binary Search Tree',
                    'Binary Tree', 'Bit Manipulation', 'Breadth-First Search',
                    'Combinatorics', 'Database', 'Depth-First Search', 'Divide and Conquer',
                    'Dynamic Programming', 'Graph', 'Greedy', 'Hash Table',
                    'Heap (Priority Queue)', 'Linked List', 'Math', 'Matrix', 'Memoization',
                    'Monotonic Stack', 'Prefix Sum', 'Recursion', 'Segment Tree',
                    'Simulation', 'Sliding Window', 'Sorting', 'Stack', 'String',
                    'String Matching', 'Topological Sort', 'Tree', 'Trie', 'Two Pointers',
                    'Union Find', 'Difficulty_Easy', 'Difficulty_Hard', 'Difficulty_Medium']


df_beg_multi_diff_filter = df_beg_multi_diff_filter.reindex(columns=training_columns, fill_value=0)

In [147]:
df_beg_multi_diff_filter.to_csv('beginner_striver.csv',index=False)

In [141]:
random_row=df_beg_multi_diff_filter[df_beg_multi_diff_filter['Array']==1]

In [165]:
random_row

,Array,Backtracking,Binary Search,Binary Search Tree,Binary Tree,Bit Manipulation,Breadth-First Search,Combinatorics,Database,Depth-First Search,...,String,String Matching,Topological Sort,Tree,Trie,Two Pointers,Union Find,Difficulty_Easy,Difficulty_Hard,Difficulty_Medium
15,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
18,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
19,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
20,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
21,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
120,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
136,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
137,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
140,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [166]:
df_beg_multi_diff_filter_link.shape

(143,)

In [171]:
random_row=random_row.sample(n=1)

In [173]:
random_row

,Array,Backtracking,Binary Search,Binary Search Tree,Binary Tree,Bit Manipulation,Breadth-First Search,Combinatorics,Database,Depth-First Search,...,String,String Matching,Topological Sort,Tree,Trie,Two Pointers,Union Find,Difficulty_Easy,Difficulty_Hard,Difficulty_Medium
73,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [181]:
for col in random_row.columns:
    if random_row[col].iloc[0]==1:
        print(col)

Array
Binary Search
Divide and Conquer
Difficulty_Medium

In [182]:
df_beg_multi_diff_filter_link.to_csv('beg_link.csv',index=False)

In [184]:
df_beg_multi_diff_filter_link.iloc[random_row.index[0]]

'https://www.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1'